### ISSUE TITLE
Installation fails due to conflicting cryptography version

### ISSUE THREAD

**Issue by NeolithEra** [simon-weber/the-listserve-archive#12]
Hi, users are unable to run the-listserve-archive due to dependency conflict with _**cryptography**_ package. 

As shown in the following full dependency graph of **_the-listserve-archive_**, it directly requires _**cryptography==0.6.1**_，while **_pyOpenSSL==17.5.0_** requires _**cryptography>=2.1.4**_.

According to pip’s _“first found wins”_ installation strategy, _**cryptography==0.6.1**_ is the actually installed version. 
However, _**cryptography==0.6.1**_ does not satisfy _**cryptography>=2.1.4**_.

### Dependency tree
```
the-listserve-archive-master
| +-cffi(version range:==0.8.6)
| | +-pycparser(version range:*)
| +-cryptography(version range:==0.6.1)
| +-decorator(version range:==3.4.0)
| +-flask(version range:==0.12.3)
| | +-click(version range:>=2.0)
| | +-itsdangerous(version range:>=0.21)
| | +-jinja2(version range:>=2.4)
| | | +-markupsafe(version range:*)
| | +-werkzeug(version range:>=0.7)
| +-itsdangerous(version range:==0.24)
| +-jinja2(version range:==2.7.3)
| | +-markupsafe(version range:*)
| +-markupsafe(version range:==0.23)
| +-ndg-httpsclient(version range:==0.3.2)
| +-pyasn1(version range:==0.1.7)
| +-pycparser(version range:==2.10)
| +-pygithub(version range:==1.25.2)
| +-pyopenssl(version range:==17.5.0)
| | +-cryptography(version range:>=2.1.4)
| | +-six(version range:>=1.5.2)
| +-python-slugify(version range:==0.1.0)
| +-pytz(version range:==2014.7)
| +-pyyaml(version range:==3.11)
| +-rauth(version range:==0.7.0)
| | +-requests(version range:>=1.2.3)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.8)
| | | +-urllib3(version range:>=1.21.1,<1.25)
| +-requests(version range:==2.20.0)
| | +-certifi(version range:>=2017.4.17)
| | +-chardet(version range:<3.1.0,>=3.0.2)
| | +-idna(version range:>=2.5,<2.8)
| | +-urllib3(version range:>=1.21.1,<1.25)
| +-six(version range:==1.8.0)
| +-unidecode(version range:==0.4.16)
| +-werkzeug(version range:==0.9.6)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

Fix your direct dependency to be **_cryptography>=2.1.4_**. 
I have checked this revision will not affect your downstream projects now.

@simon-weber  May I submmit a PR to fix it?

**Comment by simon-weber** [comment]
This isn't an installable package and isn't in active use; there's no reason to fix this.

This was an automated issue judging by your account history. I don't know what the current state of the ToS is, but I know automated drive-by improvements were [frowned upon by GitHub in the past](https://www.wired.com/2012/12/github-bots/) -- and regardless of GitHub's view, I dislike them. Please be thoughtful of maintainer's time and reconsider your approach.
